/* PTA適正化推進委員会 — site.js v25 */
const SUPPORT_URL='/support.html';
const CONTACT_URL='/contact.html';
const SITE_INDEX=[
  {title:'トップ',url:'/index.html',desc:'PTA適正化推進委員会の入口。任意加入、公私分離、個人情報、会費徴収、学校関与の全体像。'},
  {title:'保護者の方へ',url:'/guide-parent.html',desc:'入会、退会、会費、個人情報、役員強制に悩む保護者向けの説明。'},
  {title:'PTA役員の方へ',url:'/guide-pta.html',desc:'役員を責めず、入会記録、会計、個人情報、学校との分離を点検する。'},
  {title:'教育委員会・学校の方へ',url:'/guide-board.html',desc:'学校が関与する範囲を自己診断する行政・学校管理職向けの説明。'},
  {title:'教育委員会の回答',url:'/board-responses.html',desc:'76自治体・111件の回答を整理。任意加入、会費徴収、個人情報、学校関与。'},
  {title:'学校別資料館（厚木市先行収録）',url:'/national-archive.html',desc:'厚木市を先行収録した学校別PTA文書資料館。'},
  {title:'論考・調査報告',url:'/journal.html',desc:'PTA運営の法的構造、行政対応、判例、制度史、調査報告の論考。'},
  {title:'運営チェック',url:'/audit/index.html',desc:'PTA運営を点検するためのチェックツール。'},
  {title:'応援',url:SUPPORT_URL,desc:'公文書開示、資料整理、Web公開、自治体・学校への働きかけを継続するための支援。'},
  {title:'お問い合わせ・相談',url:CONTACT_URL,desc:'PTA文書、学校配布物、教育委員会回答、相談事例などの窓口。'},
  {title:'入会手続',url:'/membership.html',desc:'みなし加入・オプトアウト方式・入会契約の問題を扱う研究ノート。'},
  {title:'個人情報',url:'/privacy.html',desc:'学校からPTAへの名簿提供、目的外利用、第三者提供の問題を扱う研究ノート。'},
  {title:'会費徴収',url:'/fee-collection.html',desc:'学校徴収金との抱合せ、代理徴収、無権代理、不当利得の問題を扱う研究ノート。'},
  {title:'教職員関与',url:'/personnel.html',desc:'勤務時間内PTA事務、職専免、服務上の問題を扱う研究ノート。'},
  {title:'施設利用',url:'/facilities.html',desc:'学校教育法137条、学校施設利用、PTA室、コピー機、鍵、光熱費の問題を扱う研究ノート。'},
  {title:'法制度マップ',url:'/law-map.html',desc:'憲法、民法、消費者契約法、個人情報保護法、地方公務員法などの整理。'},
  {title:'判例整理',url:'/cases.html',desc:'PTA関連裁判例、和解、判例報道の整理。'}
];
const path=location.pathname;
const isPage=n=>path==='/'&&n==='index.html'||path.endsWith('/'+n)||path.endsWith(n);
function addGlobalStyle(){
  if(document.getElementById('pta-v22-style'))return;
  const s=document.createElement('style');s.id='pta-v22-style';s.textContent=`
  .support-strip,.support-banner,.top-support,.donation-strip{display:none!important}
  .desktop-nav{gap:14px!important}.desktop-nav>.btn-gold{display:none!important}
  .pta-v22-panel{background:#fff;border:1px solid #dbe4ee;border-left:7px solid #d4af37;border-radius:0 18px 18px 0;padding:24px 26px;margin:28px auto;box-shadow:0 12px 30px rgba(15,39,66,.06);max-width:1120px;box-sizing:border-box}
  .pta-v22-panel h2,.pta-v22-panel h3{font-family:'Noto Serif JP',serif;color:#0f2742;margin:.1em 0 .7em;line-height:1.45}.pta-v22-panel h2{font-size:clamp(1.35rem,2.4vw,2rem)}.pta-v22-panel h3{font-size:1.16rem}
  .pta-v22-panel p{line-height:1.95;color:#243244;margin:.55em 0}.pta-v22-panel ul,.pta-v22-panel ol{margin:.6em 0 0 1.3em;padding:0}.pta-v22-panel li{line-height:1.9;margin:.25em 0;color:#243244}.pta-v22-kicker{font-size:.75rem;font-weight:900;letter-spacing:.14em;color:#64748b;text-transform:uppercase;margin-bottom:8px}.pta-v22-note{background:#f8fafc;border-left:5px solid #17345c;padding:16px 18px;margin:18px 0;line-height:1.9}.pta-v22-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.pta-v22-grid a,.pta-v22-button{display:block;text-decoration:none;color:#0f2742;background:#fff;border:1px solid #dbe4ee;border-left:5px solid #d4af37;border-radius:0 14px 14px 0;padding:16px 18px;font-weight:900}.pta-v22-grid a span{display:block;font-weight:500;color:#64748b;font-size:.86rem;line-height:1.75;margin-top:6px}.pta-v22-grid a:hover,.pta-v22-button:hover{border-color:#c2410c;border-left-color:#c2410c;color:#c2410c;box-shadow:0 12px 28px rgba(194,65,12,.12)}.pta-v22-list{display:grid;gap:10px;margin-top:16px}.pta-v22-check{background:#fff;border:1px solid #e2e8f0;border-left:4px solid #17345c;border-radius:0 12px 12px 0;padding:13px 16px;line-height:1.85}.pta-v22-warning{border-left-color:#c2410c;background:#fff7ed}.pta-v22-quote{font-family:'Noto Serif JP',serif;font-weight:700;color:#0f2742}.pta-v22-small{font-size:.9rem;color:#64748b}.footer a[href*='donate']{display:inline-flex!important}@media(max-width:780px){.pta-v22-grid{grid-template-columns:1fr}.pta-v22-panel{margin:22px 16px;padding:20px 18px}.desktop-nav{gap:8px!important}.nav-link{font-size:.82rem!important}}
  `;document.head.appendChild(s);
}
function removeTopDonation(){document.querySelectorAll('.support-strip,.support-banner,.top-support,.donation-strip').forEach(e=>e.remove())}
function initPrimaryNavigation(){
  const desktop=document.querySelector('.desktop-nav');
  if(desktop){desktop.innerHTML=`<a class="nav-link" href="/index.html">トップ</a><div class="nav-item has-dropdown"><a class="nav-link" href="#">立場別</a><div class="mega-menu"><div class="mega-col"><h4>立場別</h4><ul><li><a href="/guide-parent.html">保護者の方へ</a></li><li><a href="/guide-pta.html">PTA役員の方へ</a></li><li><a href="/guide-board.html">教育委員会・学校の方へ</a></li></ul></div></div></div><div class="nav-item has-dropdown"><a class="nav-link" href="#">資料・データ</a><div class="mega-menu"><div class="mega-col"><h4>一次資料</h4><ul><li><a href="/board-responses.html">教育委員会の回答</a></li><li><a href="/national-archive.html">学校別資料館（厚木市先行収録）</a></li><li><a href="/administrative-materials.html">行政資料整理</a></li></ul></div></div></div><div class="nav-item has-dropdown"><a class="nav-link" href="/journal.html">研究</a><div class="mega-menu"><div class="mega-col"><h4>論考・整理</h4><ul><li><a href="/journal.html">論考・調査報告</a></li><li><a href="/report.html">総合分析レポート</a></li><li><a href="/law-map.html">法制度マップ</a></li><li><a href="/cases.html">判例整理</a></li><li><a href="/timeline.html">PTA制度史</a></li></ul></div><div class="mega-col"><h4>論点別</h4><ul><li><a href="/membership.html">入会手続</a></li><li><a href="/privacy.html">個人情報</a></li><li><a href="/fee-collection.html">会費徴収</a></li><li><a href="/personnel.html">教職員関与</a></li><li><a href="/facilities.html">施設利用</a></li></ul></div></div></div><div class="nav-item has-dropdown"><a class="nav-link" href="#">ツール</a><div class="mega-menu"><div class="mega-col"><h4>点検用</h4><ul><li><a href="/audit/index.html">運営チェックアプリ</a></li><li><a href="/guideline.html">適正化ガイドライン</a></li></ul></div></div></div><a class="nav-link support-nav-link" href="${SUPPORT_URL}">応援</a>`}
  const mobile=document.getElementById('mobileOverlay');
  if(mobile){mobile.innerHTML=`<a class="mobile-link" href="/index.html"><span>Top</span>トップ</a><a class="mobile-link" href="/guide-parent.html"><span>Parents</span>保護者の方へ</a><a class="mobile-link" href="/guide-pta.html"><span>PTA Board</span>PTA役員の方へ</a><a class="mobile-link" href="/guide-board.html"><span>School / Board</span>教育委員会・学校の方へ</a><a class="mobile-link" href="/board-responses.html"><span>Responses</span>教育委員会の回答</a><a class="mobile-link" href="/national-archive.html"><span>Documents</span>学校別資料館</a><a class="mobile-link" href="/journal.html"><span>Research</span>研究</a><a class="mobile-link" href="/audit/index.html"><span>Tools</span>運営チェック</a><a class="mobile-link support-mobile-link" href="${SUPPORT_URL}"><span>Support</span>応援</a><a class="mobile-link" href="${CONTACT_URL}"><span>Contact</span>相談・情報提供</a><div class="close-overlay" id="closeOverlay">CLOSE ×</div>`}
}
function initSearch(){document.querySelectorAll('.search-input').forEach(input=>{const dd=input.closest('.header-search')?.querySelector('.search-results-dropdown');if(!dd)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(q.length<2){dd.classList.remove('is-open');return}const hits=SITE_INDEX.filter(p=>(p.title+p.desc).toLowerCase().includes(q)).slice(0,8);dd.innerHTML=hits.length?hits.map(p=>`<a href="${p.url}" class="srd-item"><div class="srd-item-title">${p.title}</div><div class="srd-item-desc">${p.desc}</div></a>`).join(''):`<div class="srd-empty">「${input.value}」に一致するページが見つかりません</div>`;dd.classList.add('is-open')});document.addEventListener('click',e=>{if(!input.closest('.header-search')?.contains(e.target))dd.classList.remove('is-open')})})}
function initHamburger(){const btn=document.getElementById('hamburger'),ol=document.getElementById('mobileOverlay');if(!btn||!ol)return;const close=()=>{ol.classList.remove('is-open');btn.setAttribute('aria-expanded','false')};btn.addEventListener('click',()=>{ol.classList.add('is-open');btn.setAttribute('aria-expanded','true')});ol.querySelector('#closeOverlay')?.addEventListener('click',close)}
function initMegaMenu(){document.querySelectorAll('.nav-item.has-dropdown>.nav-link').forEach(link=>{link.addEventListener('click',e=>{const item=link.closest('.nav-item');if(link.getAttribute('href')==='#')e.preventDefault();item.classList.toggle('is-open');document.querySelectorAll('.nav-item.is-open').forEach(i=>{if(i!==item)i.classList.remove('is-open')})})});document.addEventListener('click',e=>{if(!e.target.closest('.nav-item'))document.querySelectorAll('.nav-item.is-open').forEach(i=>i.classList.remove('is-open'))})}
function initFAQ(){document.querySelectorAll('.faq-item').forEach(item=>{const q=item.querySelector('.faq-q');if(q)q.addEventListener('click',()=>{const o=item.classList.toggle('is-open');const t=item.querySelector('.faq-toggle');if(t)t.textContent=o?'▲':'▼'})})}
function initChecklist(){document.querySelectorAll('.check-box').forEach(box=>box.addEventListener('click',()=>{box.classList.toggle('checked');box.textContent=box.classList.contains('checked')?'✓':''}))}
function insertAfterHero(html,id){if(document.getElementById(id))return;const hero=document.querySelector('.hero,.hero-section,.top-hero,.main-visual,.page-hero');if(hero)hero.insertAdjacentHTML('afterend',html);else document.querySelector('main')?.insertAdjacentHTML('afterbegin',html)}
function insertAfterHomePhotoHero(html,id){if(document.getElementById(id))return;const photoHero=document.querySelector('.home-photo-hero');if(photoHero){photoHero.insertAdjacentHTML('afterend',html);return}insertAfterHero(html,id)}
function initHomeProof(){if(!isPage('index.html'))return;insertAfterHomePhotoHero(`<section class="pta-v22-panel" id="response-proof-v22"><div class="pta-v22-kicker">Administrative responses</div><h2>76自治体・111件の回答から、学校とPTAの線引きを確認する。</h2><p>このサイトの根拠は、抽象的な主張だけではありません。教育委員会からの回答、学校別資料、公開資料を照合し、任意加入、会費徴収、個人情報、教職員関与、学校施設利用の論点を整理しています。</p><div class="pta-v22-grid"><a href="/guide-board.html">学校・教育委員会向け<span>まず学校側の関与範囲を自己診断する。</span></a><a href="/board-responses.html">教育委員会の回答<span>76自治体・111件の回答を確認する。</span></a><a href="/national-archive.html">学校別資料館<span>厚木市を先行収録した実際の資料を見る。</span></a></div></section>`,'response-proof-v22')}
function initGuideBoardPatch(){if(!isPage('guide-board.html'))return;insertAfterHero(`<section class="pta-v22-panel" id="board-bluf-v22"><div class="pta-v22-kicker">For school boards</div><h2>問題はPTAの存在ではなく、学校手続に溶け込むことです。</h2><p class="pta-v22-quote">入会、名簿、徴収、会計、連絡、役員選出を学校から切り離せば、多くのリスクは同時にほどけます。</p><div class="pta-v22-list"><div class="pta-v22-check">入会申込記録を、会員ごとに確認できますか。</div><div class="pta-v22-check">PTA会費徴収に、学校徴収金・学校口座・学校保有情報を使っていませんか。</div><div class="pta-v22-check">PTA名簿、役員候補者名簿、連絡網を学校保有情報から作っていませんか。</div><div class="pta-v22-check">教職員が勤務時間中にPTA会計、集金、名簿、役員選出、未納督促をしていませんか。</div><div class="pta-v22-check">学校施設、学校アプリ、入学説明会、児童経由配布がPTA加入圧力になっていませんか。</div></div><div class="pta-v22-grid" style="margin-top:18px"><a href="/board-responses.html">他自治体の回答を見る<span>76自治体・111件の整理へ。</span></a><a href="/personnel.html">教職員関与を読む<span>職専免・服務の論点へ。</span></a><a href="/privacy.html">個人情報を読む<span>学校保有情報の目的外利用へ。</span></a></div></section>`,'board-bluf-v22');const main=document.querySelector('main')||document.body;const html=`<section class="pta-v22-panel" id="worktime-duty-v22"><div class="pta-v22-kicker">勤務時間・職専免</div><h2>勤務時間中のPTA業務は、校務にも職務専念義務免除にも当たりません。</h2><p>PTAは学校とは別の任意団体です。会費徴収、会計、会員管理、役員選出、総会資料作成、未納督促、PTA通知作成は、PTA内部の団体事務であり、学校教育そのものではありません。</p><p>これを「校務」と呼んでも、実質が私的団体の内部事務である以上、公務にはなりません。逆に「職務専念義務免除」として処理しようとする場合も、職免は本来の職務から離れることを例外的に認める制度であり、任意団体PTAの内部運営を勤務時間中に処理する一般的な受け皿ではありません。</p><div class="pta-v22-note pta-v22-warning"><strong>確認すべき矛盾</strong><br>PTAが任意団体であるなら、その内部事務は公務ではありません。PTAが行政運営上不可欠な団体だというなら、社会教育関係団体としての独立性、公私分離、社会教育法12条との整合が問われます。</div><p>教育委員会は、教職員が勤務時間中にPTA事務を行っている実態について、校務命令、職専免、兼職兼業、PTAからの委任、学校徴収金事務のいずれで処理しているのかを文書で説明できる状態にする必要があります。説明できない場合は、学校協力を停止し、PTAが自ら処理する運用へ切り替えるべきです。</p></section><section class="pta-v22-panel" id="pipc-selfcheck-v22"><div class="pta-v22-kicker">個人情報保護法</div><h2>学校保有情報をPTA運営に使えるかは、利用目的・同意・委託関係で自己診断する問題です。</h2><p>個人情報保護委員会資料は、学校からPTAへの提供を無条件に認める資料ではありません。入口は、学校業務に関する法令上の所掌事務又は業務の範囲内として、利用目的を具体的に特定・公表しているかです。</p><ul><li>PTA会員管理、会費徴収、役員候補者名簿、PTA内部連絡は、学校教育のための児童生徒情報利用ですか。</li><li>本人同意を根拠にする場合、学校手続と混同しない自由な同意として取得されていますか。</li><li>委託と整理する場合、委託契約、監督義務、漏えい時の報告義務を説明できますか。</li></ul><p class="pta-v22-note">適正な出発点は、PTAが入会を希望する保護者から、入会申込書等により直接情報を取得することです。学校名簿、学校連絡アプリ、学校徴収金口座をPTA運営に流用しないことが、公私分離の実務です。</p></section>`;if(!document.getElementById('worktime-duty-v22')){const target=document.getElementById('board-privacy-entry')||document.getElementById('article137-school-use')||main.firstElementChild;target?target.insertAdjacentHTML('beforebegin',html):main.insertAdjacentHTML('afterbegin',html)}}
function initPersonnelPatch(){if(!isPage('personnel.html')||document.getElementById('personnel-duty-conclusion-v24'))return;insertAfterHero(`<section class="pta-v22-panel" id="personnel-duty-conclusion-v24"><div class="pta-v22-kicker">結論：勤務時間・職専免</div><h2>PTA内部事務は、校務にも職務専念義務免除にも乗せられません。</h2><p>教職員が学校とPTAの連絡調整を行う場面はあり得ます。しかし、PTA会費徴収、会計、会員名簿、役員選出、総会資料作成、未納督促、PTA通知作成は、PTAという別団体の内部事務です。</p><p>勤務時間中にこれらを処理することは、地方公共団体がなすべき職務ではありません。これを校務と呼んでも実質は変わらず、職務専念義務免除を使っても、任意団体の内部運営を恒常的に処理する一般的根拠にはなりません。</p><div class="pta-v22-note pta-v22-warning"><strong>教育委員会が確認すべき点</strong><br>校務命令、職専免、兼職兼業、PTAからの委任、学校徴収金事務のいずれの整理であっても、対象者、時間、用務、根拠規則、記録を示せなければ、学校がPTA内部事務を肩代わりしている状態です。</div><p>是正の方向は、教職員を責めることではありません。PTA内部事務をPTAへ戻し、学校側は施設利用、安全管理、学校行事との調整など、学校管理上必要な連絡調整に限定することです。</p></section>`,'personnel-duty-conclusion-v24')}
function initGuidePtaPatch(){if(!isPage('guide-pta.html')||document.getElementById('pta-cover-v25'))return;insertAfterHero(`<section class="pta-v22-panel" id="pta-cover-v25"><div class="pta-v22-kicker">PTA役員の方へ</div><h2>これは、役員個人を責める話ではありません。</h2><p>このページは、PTA活動の価値を否定するものではありません。多くの役員は、前年度から引き継がれた仕組みの中で、忙しい中、善意で運営を支えてきました。問題は、個々の役員の人格や努力ではなく、長年続いてきた学校依存の仕組みです。</p><p class="pta-v22-note">適正化とは、役員の仕事と責任を増やすことではなく、減らすことです。入会記録、会費徴収、個人情報、会計をPTA自身の手続に戻すことで、怒る保護者への対応、説明不能な会費請求、名簿利用、個人責任リスクを減らせます。</p><div class="pta-v22-list"><div class="pta-v22-check"><strong>入会記録</strong><br>入会申込記録がなければ、誰が会員なのか、誰に会費を請求できるのかを説明できません。</div><div class="pta-v22-check"><strong>個人情報</strong><br>学校名簿や学校アプリに依存すると、PTA自身が情報を適正に取得したと言いにくくなります。</div><div class="pta-v22-check"><strong>会計</strong><br>学校徴収金と一緒に処理すると、未加入者、退会者、非会員の扱いが不透明になります。</div><div class="pta-v22-check"><strong>役員保護</strong><br>学校は協力者に見えても、法的には別団体です。学校依存をやめることは、PTA役員を守るための分離です。</div></div><p style="margin-top:18px"><a class="pta-v22-button" href="/board-responses.html">他自治体の回答を見る</a></p></section>`,'pta-cover-v25')}
function initGuideParentPatch(){if(!isPage('guide-parent.html')||document.getElementById('parent-safe-v25'))return;insertAfterHero(`<section class="pta-v22-panel" id="parent-safe-v25"><div class="pta-v22-kicker">まず安心するために</div><h2>お子さんへの不利益が心配な方へ。</h2><p>退会や非加入を考えたときに、「子どもが困るのではないか」と不安になるのは自然です。PTA問題で多くの保護者が最初に感じる不安は、法律論ではなく、子どもへの影響です。</p><p>非加入を理由に学校行事や教育活動で子どもを不利益に扱うことは、学校側にとっても大きなリスクです。ただし、現場で不適切な扱いが起きる可能性をゼロとは言えません。だからこそ、感情的に争うのではなく、文書と記録で整理します。</p><div class="pta-v22-grid"><a href="#" onclick="return false">まず安心したい<span>非加入を理由に子どもを責める必要はありません。</span></a><a href="#" onclick="return false">手元の文書を確認したい<span>入会申込書、会費案内、学校徴収金通知を保存してください。</span></a><a href="#" onclick="return false">相談したい<span>学校だけでなく、教育委員会への相談書として整理できます。</span></a></div><div class="pta-v22-list"><div class="pta-v22-check">不利益が心配な場合は、まず「いつ・誰が・どの文書で・どのように説明したか」を残してください。</div><div class="pta-v22-check">子どもに関わる差異が起きた場合は、学校行事なのか、PTA行事なのか、費用負担と主催者を分けて確認してください。</div><div class="pta-v22-check">入会しない人から非加入届や不同意届を集める方式は、非会員情報の取得・管理という別の問題を生みます。</div></div><p style="margin-top:18px"><a class="pta-v22-button" href="/contact.html">相談・情報提供の窓口へ</a></p></section>`,'parent-safe-v25')}
function initContactPatch(){if(!isPage('contact.html'))return;insertAfterHero(`<section class="pta-v22-panel" id="contact-consult-v22"><div class="pta-v22-kicker">相談・情報提供</div><h2>PTAで困っている方も、相談としてお送りください。</h2><p>退会、非加入、会費、名簿、学校からの圧力、子どもへの不利益が心配な場合も、情報提供だけでなく相談として受け付けます。</p><p class="pta-v22-note">送付前に、児童名、住所、電話番号、口座番号など、公開を望まない個人情報は可能な範囲でマスキングしてください。文書の種類、学校・自治体名、配布時期、どのような説明を受けたかが分かると整理しやすくなります。</p></section>`,'contact-consult-v22')}
function initArchivePatch(){if(!isPage('national-archive.html'))return;document.querySelectorAll('h1,h2,.section-title').forEach(e=>{if(e.textContent.includes('全国PTA資料館')||e.textContent.includes('全国資料館'))e.textContent=e.textContent.replace('全国PTA資料館','学校別資料館（厚木市先行収録）').replace('全国資料館','学校別資料館（厚木市先行収録）')});insertAfterHero(`<section class="pta-v22-panel" id="archive-scope-v22"><div class="pta-v22-kicker">収録範囲</div><h2>この資料館は、厚木市資料を先行収録しています。</h2><p>名称や導線だけで全国全校を網羅しているように見えないよう、現在の収録範囲を明示します。今後、他自治体の資料を順次追加していく前提ですが、現時点では厚木市の学校別資料が中心です。</p></section>`,'archive-scope-v22')}
function initBoardResponsesPatch(){if(!isPage('board-responses.html'))return;insertAfterHero(`<section class="pta-v22-panel" id="responses-count-v22"><div class="pta-v22-kicker">回答DB</div><h2>76自治体・111件の回答を、学校とPTAの線引き資料として整理しています。</h2><p>このページは、行政側の公式回答を確認するための資料です。任意加入、会費徴収、個人情報、学校関与、施設利用、教職員関与の論点を、自治体回答から照合できます。</p></section>`,'responses-count-v22')}
function initCasesPatch(){if(!isPage('cases.html'))return;insertAfterHero(`<section class="pta-v22-panel" id="cases-caution-v22"><div class="pta-v22-kicker">判例の読み方</div><h2>判例は、過大に読まず、到達点を限定して扱います。</h2><p>熊本訴訟やコサージュ事件は、PTAの任意加入を否定した判例ではありません。一方で、強制加入一般を違法と認定した判例としても整理しません。公式PDF未確認のものは、その限界を明示して扱います。</p></section>`,'cases-caution-v22')}
document.addEventListener('DOMContentLoaded',()=>{addGlobalStyle();removeTopDonation();initPrimaryNavigation();initSearch();initMegaMenu();initHamburger();initFAQ();initChecklist();initHomeProof();initGuideBoardPatch();initPersonnelPatch();initGuidePtaPatch();initGuideParentPatch();initContactPatch();initArchivePatch();initBoardResponsesPatch();initCasesPatch()});