/* PTA適正化推進委員会 — site.js v29 compact */
const SUPPORT_URL='/support.html';
const CONTACT_URL='/contact.html';
const path=location.pathname;
const isPage=n=>(path==='/'&&n==='index.html')||path.endsWith('/'+n)||path.endsWith(n);
const SITE_INDEX=[
 ['トップ','/index.html','任意加入、公私分離、個人情報、会費徴収、学校関与の全体像。'],
 ['保護者の方へ','/guide-parent.html','退会、非加入、会費、個人情報、役員強制に悩む保護者向け。'],
 ['PTA役員の方へ','/guide-pta.html','役員を責めず、入会記録、会計、個人情報、学校との分離を点検。'],
 ['教育委員会・学校の方へ','/guide-board.html','学校が関与する範囲を自己診断する行政・学校管理職向け。'],
 ['教育委員会の回答','/board-responses.html','76自治体・111件の回答。'],
 ['全国資料館','/national-archive.html','自治体別・学校別のPTA実物文書アーカイブ。'],
 ['論考・調査報告','/journal.html','PTA運営の法的構造、行政対応、判例、制度史。'],
 ['運営チェック','/audit/index.html','PTA運営を点検するためのチェックツール。'],
 ['お問い合わせ・相談',CONTACT_URL,'相談・情報提供の窓口。']
];
function addGlobalStyle(){
 if(document.getElementById('pta-v29-style'))return;
 const s=document.createElement('style');s.id='pta-v29-style';s.textContent=`
 .support-strip,.support-banner,.top-support,.donation-strip{display:none!important}.desktop-nav{gap:14px!important}.desktop-nav>.btn-gold{display:none!important}
 .pta-panel{background:#fff;border:1px solid #dbe4ee;border-left:7px solid #d4af37;border-radius:0 18px 18px 0;padding:24px 26px;margin:28px auto;box-shadow:0 12px 30px rgba(15,39,66,.06);max-width:1120px;box-sizing:border-box}.pta-panel h2{font-family:'Noto Serif JP',serif;color:#0f2742;margin:.1em 0 .7em;line-height:1.45;font-size:clamp(1.35rem,2.4vw,2rem)}.pta-panel p{line-height:1.95;color:#243244;margin:.55em 0}.pta-kicker{font-size:.75rem;font-weight:900;letter-spacing:.14em;color:#64748b;text-transform:uppercase;margin-bottom:8px}.pta-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.pta-grid a,.pta-button{display:block;text-decoration:none;color:#0f2742;background:#fff;border:1px solid #dbe4ee;border-left:5px solid #d4af37;border-radius:0 14px 14px 0;padding:16px 18px;font-weight:900}.pta-grid a span{display:block;font-weight:500;color:#64748b;font-size:.86rem;line-height:1.75;margin-top:6px}.pta-list{display:grid;gap:10px;margin-top:16px}.pta-check{background:#fff;border:1px solid #e2e8f0;border-left:4px solid #17345c;border-radius:0 12px 12px 0;padding:13px 16px;line-height:1.85}.pta-quote{font-family:'Noto Serif JP',serif;font-weight:700;color:#0f2742}
 #ppc-selfcheck-v22{display:none!important}.worktime-duty-section{background:#fff!important;border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;padding:0!important}.board-auto-accordion{background:#fff;border:1px solid #dbe4ee;border-radius:14px;margin:0 0 16px;overflow:hidden;box-shadow:0 8px 22px rgba(15,39,66,.05)}.board-auto-accordion summary{font-family:'Noto Serif JP',serif;font-size:clamp(1.45rem,2.6vw,2.15rem)!important;line-height:1.42!important;font-weight:900;color:#1e3a5f;border-left:7px solid #d4af37;padding:22px 24px;cursor:pointer;list-style:none;display:flex;align-items:center;justify-content:space-between;background:#fff;gap:18px}.board-auto-accordion summary::-webkit-details-marker{display:none}.board-auto-accordion summary::after{content:'＋';font-family:system-ui,sans-serif;font-size:1.45rem;color:#d4af37;font-weight:900;flex-shrink:0}.board-auto-accordion[open] summary::after{content:'−'}.board-auto-accordion[open] summary{background:#f8fafc;border-bottom:1px solid #e2e8f0}.board-auto-accordion .chapter-content{padding:24px 28px 30px;line-height:1.95;color:#1e293b}.board-auto-accordion .section-lead{font-size:1rem!important;line-height:1.95!important}.board-auto-accordion .section-kicker{display:none!important}
 .national-archive-page .atsugi-schools-section{background:#fff!important;padding:46px 0 56px!important;border-bottom:1px solid var(--line)!important}.national-archive-page .atsugi-schools-head{display:none!important}.national-archive-page .atsugi-detail{margin-top:0!important}.national-archive-page .archive-map-section{padding-top:56px!important}
 @media(max-width:780px){.pta-grid{grid-template-columns:1fr}.pta-panel{margin:22px 16px;padding:20px 18px}.desktop-nav{gap:8px!important}.nav-link{font-size:.82rem!important}.board-auto-accordion summary{font-size:1.28rem!important;padding:18px 18px}.board-auto-accordion .chapter-content{padding:20px 18px}}
 `;document.head.appendChild(s);
}
function removeTopDonation(){document.querySelectorAll('.support-strip,.support-banner,.top-support,.donation-strip').forEach(e=>e.remove())}
function initPrimaryNavigation(){
 const d=document.querySelector('.desktop-nav');
 if(d)d.innerHTML='<a class="nav-link" href="/index.html">トップ</a><div class="nav-item has-dropdown"><a class="nav-link" href="#">立場別</a><div class="mega-menu"><div class="mega-col"><h4>立場別</h4><ul><li><a href="/guide-parent.html">保護者の方へ</a></li><li><a href="/guide-pta.html">PTA役員の方へ</a></li><li><a href="/guide-board.html">教育委員会・学校の方へ</a></li></ul></div></div></div><div class="nav-item has-dropdown"><a class="nav-link" href="#">資料・データ</a><div class="mega-menu"><div class="mega-col"><h4>一次資料</h4><ul><li><a href="/board-responses.html">教育委員会の回答</a></li><li><a href="/national-archive.html">全国資料館</a></li><li><a href="/administrative-materials.html">行政資料整理</a></li></ul></div></div></div><div class="nav-item has-dropdown"><a class="nav-link" href="/journal.html">研究</a><div class="mega-menu"><div class="mega-col"><h4>論考・整理</h4><ul><li><a href="/journal.html">論考・調査報告</a></li><li><a href="/report.html">総合分析レポート</a></li><li><a href="/law-map.html">法制度マップ</a></li><li><a href="/cases.html">判例整理</a></li><li><a href="/timeline.html">PTA制度史</a></li></ul></div><div class="mega-col"><h4>論点別</h4><ul><li><a href="/membership.html">入会手続</a></li><li><a href="/privacy.html">個人情報</a></li><li><a href="/fee-collection.html">会費徴収</a></li><li><a href="/personnel.html">教職員関与</a></li><li><a href="/facilities.html">施設利用</a></li></ul></div></div></div><div class="nav-item has-dropdown"><a class="nav-link" href="#">ツール</a><div class="mega-menu"><div class="mega-col"><h4>点検用</h4><ul><li><a href="/audit/index.html">運営チェックアプリ</a></li><li><a href="/guideline.html">適正化ガイドライン</a></li></ul></div></div></div><a class="nav-link support-nav-link" href="'+SUPPORT_URL+'">応援</a>';
 const m=document.getElementById('mobileOverlay');
 if(m)m.innerHTML='<a class="mobile-link" href="/index.html"><span>Top</span>トップ</a><a class="mobile-link" href="/guide-parent.html"><span>Parents</span>保護者の方へ</a><a class="mobile-link" href="/guide-pta.html"><span>PTA Board</span>PTA役員の方へ</a><a class="mobile-link" href="/guide-board.html"><span>School / Board</span>教育委員会・学校の方へ</a><a class="mobile-link" href="/board-responses.html"><span>Responses</span>教育委員会の回答</a><a class="mobile-link" href="/national-archive.html"><span>Archive</span>全国資料館</a><a class="mobile-link" href="/journal.html"><span>Research</span>研究</a><a class="mobile-link" href="/audit/index.html"><span>Tools</span>運営チェック</a><a class="mobile-link support-mobile-link" href="'+SUPPORT_URL+'"><span>Support</span>応援</a><a class="mobile-link" href="'+CONTACT_URL+'"><span>Contact</span>相談・情報提供</a><div class="close-overlay" id="closeOverlay">CLOSE ×</div>';
}
function initSearch(){document.querySelectorAll('.search-input').forEach(input=>{const dd=input.closest('.header-search')?.querySelector('.search-results-dropdown');if(!dd)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(q.length<2){dd.classList.remove('is-open');return}const hits=SITE_INDEX.filter(p=>(p[0]+p[2]).toLowerCase().includes(q)).slice(0,8);dd.innerHTML=hits.length?hits.map(p=>'<a href="'+p[1]+'" class="srd-item"><div class="srd-item-title">'+p[0]+'</div><div class="srd-item-desc">'+p[2]+'</div></a>').join(''):'<div class="srd-empty">一致するページが見つかりません</div>';dd.classList.add('is-open')});document.addEventListener('click',e=>{if(!input.closest('.header-search')?.contains(e.target))dd.classList.remove('is-open')})})}
function initHamburger(){const b=document.getElementById('hamburger'),o=document.getElementById('mobileOverlay');if(!b||!o)return;const close=()=>{o.classList.remove('is-open');b.setAttribute('aria-expanded','false')};b.addEventListener('click',()=>{o.classList.add('is-open');b.setAttribute('aria-expanded','true')});o.querySelector('#closeOverlay')?.addEventListener('click',close)}
function initMegaMenu(){document.querySelectorAll('.nav-item.has-dropdown>.nav-link').forEach(link=>link.addEventListener('click',e=>{const item=link.closest('.nav-item');if(link.getAttribute('href')==='#')e.preventDefault();item.classList.toggle('is-open');document.querySelectorAll('.nav-item.is-open').forEach(i=>{if(i!==item)i.classList.remove('is-open')})}));document.addEventListener('click',e=>{if(!e.target.closest('.nav-item'))document.querySelectorAll('.nav-item.is-open').forEach(i=>i.classList.remove('is-open'))})}
function initFAQ(){document.querySelectorAll('.faq-item').forEach(item=>{const q=item.querySelector('.faq-q');if(q)q.addEventListener('click',()=>item.classList.toggle('is-open'))})}
function initChecklist(){document.querySelectorAll('.check-box').forEach(box=>box.addEventListener('click',()=>{box.classList.toggle('checked');box.textContent=box.classList.contains('checked')?'✓':''}))}
function insertAfterHero(html,id){if(document.getElementById(id))return;const h=document.querySelector('.hero,.hero-section,.top-hero,.main-visual,.page-hero');if(h)h.insertAdjacentHTML('afterend',html);else document.querySelector('main')?.insertAdjacentHTML('afterbegin',html)}
function insertAfterHomePhotoHero(html,id){if(document.getElementById(id))return;const h=document.querySelector('.home-photo-hero');if(h)h.insertAdjacentHTML('afterend',html);else insertAfterHero(html,id)}
function initHomeProof(){if(!isPage('index.html'))return;insertAfterHomePhotoHero('<section class="pta-panel" id="response-proof-v22"><div class="pta-kicker">Administrative responses</div><h2>76自治体・111件の回答から、学校とPTAの線引きを確認する。</h2><p>教育委員会からの回答、学校別資料、公開資料を照合し、任意加入、会費徴収、個人情報、教職員関与、学校施設利用の論点を整理しています。</p><div class="pta-grid"><a href="/guide-board.html">学校・教育委員会向け<span>学校側の関与範囲を自己診断する。</span></a><a href="/board-responses.html">教育委員会の回答<span>76自治体・111件の回答を確認する。</span></a><a href="/national-archive.html">全国資料館<span>実際の資料を見る。</span></a></div></section>','response-proof-v22')}
function accordionizeBoardSection(sec,overrideTitle){if(!sec||sec.dataset.accordionized==='1')return;const inner=sec.querySelector('.wrap')||sec;const titleEl=inner.querySelector('.section-title')||inner.querySelector('h2,h3');const title=overrideTitle||(titleEl?titleEl.textContent.trim():'詳細');const details=document.createElement('details');details.className='board-auto-accordion';const summary=document.createElement('summary');summary.textContent=title;const content=document.createElement('div');content.className='chapter-content';Array.from(inner.childNodes).forEach(node=>{if(node.nodeType===1&&(node.matches('.section-kicker,.section-title')||node===titleEl))return;content.appendChild(node)});details.append(summary,content);inner.innerHTML='';inner.appendChild(details);sec.dataset.accordionized='1'}
function findSectionByHeadingText(txt){const hs=Array.from(document.querySelectorAll('main section h2, main section h3'));const h=hs.find(el=>el.textContent.includes(txt));return h?h.closest('section'):null}
function initGuideBoardPatch(){
 if(!isPage('guide-board.html'))return;
 document.getElementById('ppc-selfcheck-v22')?.remove();
 insertAfterHero('<section class="pta-panel" id="board-bluf-v22"><div class="pta-kicker">For school boards</div><h2>問題はPTAの存在ではなく、学校手続に溶け込むことです。</h2><p class="pta-quote">入会、名簿、徴収、会計、連絡、役員選出を学校から切り離せば、多くのリスクは同時にほどけます。</p><div class="pta-list"><div class="pta-check">入会申込記録を、会員ごとに確認できますか。</div><div class="pta-check">PTA会費徴収に、学校徴収金・学校口座・学校保有情報を使っていませんか。</div><div class="pta-check">PTA名簿、役員候補者名簿、連絡網を学校保有情報から作っていませんか。</div><div class="pta-check">教職員が勤務時間中にPTA会計、集金、名簿、役員選出、未納督促をしていませんか。</div></div></section>','board-bluf-v22');
 const html='<section class="board-guide-section article137-focus worktime-duty-section" id="worktime-duty-v22"><div class="wrap"><div class="section-kicker">勤務時間・職専免</div><h2 class="section-title">勤務時間中のPTA業務は、校務にも職務専念義務免除にも当たりません。</h2><p class="section-lead">PTAは学校とは別の任意団体です。会費徴収、会計、会員管理、役員選出、総会資料作成、未納督促、PTA通知作成は、PTA内部の団体事務であり、学校教育そのものではありません。</p><div class="statute-quote" style="border:2px solid #17345c;background:#f8fafc;border-radius:14px;padding:18px 20px;margin:20px 0 24px;box-shadow:0 4px 14px rgba(15,23,42,.06)"><div style="font-weight:900;color:#17345c;margin-bottom:8px;letter-spacing:.04em">地方公務員法第35条（職務専念義務）</div><p style="font-size:1.04rem;line-height:1.9;margin:0;color:#111827"><strong>職員は、その勤務時間及び職務上の注意力を、当該地方公共団体がなすべき職務に用いる必要があります。</strong></p></div><div class="chapter-content plain-prose-block" style="margin-top:18px"><p>これを「校務」と呼んでも、実質が私的団体の内部事務である以上、公務にはなりません。逆に「職務専念義務免除」として処理しようとする場合も、職免は任意団体PTAの内部運営を勤務時間中に処理する一般的な受け皿ではありません。</p><p>教育委員会は、教職員が勤務時間中にPTA事務を行っている実態について、校務命令、職専免、兼職兼業、PTAからの委任、学校徴収金事務のいずれで処理しているのかを文書で説明できる状態にする必要があります。</p></div></div></section>';
 if(!document.getElementById('worktime-duty-v22')){const target=document.getElementById('board-first-reading')||document.querySelector('main')?.firstElementChild;target?target.insertAdjacentHTML('afterend',html):document.querySelector('main')?.insertAdjacentHTML('afterbegin',html)}
 accordionizeBoardSection(document.getElementById('board-first-reading'),'教育委員会は、法令論の前に「学校が関与した事実」を確認する');
 accordionizeBoardSection(document.getElementById('worktime-duty-v22'));
 accordionizeBoardSection(findSectionByHeadingText('3分類と学校徴収金通知から'));
 ['article137-school-use','board-responsibility-essay','board-ed-resource-set','municipal-voices','board-checklist','board-response-policy'].forEach(id=>accordionizeBoardSection(document.getElementById(id)));
}
function initArchivePatch(){if(!isPage('national-archive.html'))return;document.getElementById('archive-scope-v22')?.remove();const atsugi=document.getElementById('atsugi-schools');const map=document.getElementById('archive-national-map');if(atsugi&&map&&atsugi.previousElementSibling!==map){map.parentNode.insertBefore(atsugi,map)}const h=atsugi?.querySelector('.atsugi-schools-head');if(h)h.remove()}
function initPersonnelPatch(){if(!isPage('personnel.html')||document.getElementById('personnel-duty-conclusion-v24'))return;insertAfterHero('<section class="pta-panel" id="personnel-duty-conclusion-v24"><div class="pta-kicker">結論：勤務時間・職専免</div><h2>PTA内部事務は、校務にも職務専念義務免除にも乗せられません。</h2><p>教職員が学校とPTAの連絡調整を行う場面はあり得ます。しかし、PTA会費徴収、会計、会員名簿、役員選出、総会資料作成、未納督促、PTA通知作成は、PTAという別団体の内部事務です。</p></section>','personnel-duty-conclusion-v24')}
function initGuidePtaPatch(){if(!isPage('guide-pta.html')||document.getElementById('pta-cover-v25'))return;insertAfterHero('<section class="pta-panel" id="pta-cover-v25"><div class="pta-kicker">PTA役員の方へ</div><h2>これは、役員個人を責める話ではありません。</h2><p>このページは、PTA活動の価値を否定するものではありません。問題は、個々の役員の人格や努力ではなく、長年続いてきた学校依存の仕組みです。</p></section>','pta-cover-v25')}
function initGuideParentPatch(){if(!isPage('guide-parent.html')||document.getElementById('parent-safe-v25'))return;insertAfterHero('<section class="pta-panel" id="parent-safe-v25"><div class="pta-kicker">まず安心するために</div><h2>お子さんへの不利益が心配な方へ。</h2><p>退会や非加入を考えたときに、「子どもが困るのではないか」と不安になるのは自然です。文書と記録で整理します。</p><p><a class="pta-button" href="/contact.html">相談・情報提供の窓口へ</a></p></section>','parent-safe-v25')}
function initCasesPatch(){if(!isPage('cases.html'))return;insertAfterHero('<section class="pta-panel" id="cases-caution-v22"><div class="pta-kicker">判例の読み方</div><h2>判例は、過大に読まず、到達点を限定して扱います。</h2><p>熊本訴訟やコサージュ事件は、PTAの任意加入を否定した判例ではありません。一方で、強制加入一般を違法と認定した判例としても整理しません。</p></section>','cases-caution-v22')}
document.addEventListener('DOMContentLoaded',()=>{addGlobalStyle();removeTopDonation();initPrimaryNavigation();initSearch();initMegaMenu();initHamburger();initFAQ();initChecklist();initHomeProof();initGuideBoardPatch();initArchivePatch();initPersonnelPatch();initGuidePtaPatch();initGuideParentPatch();initCasesPatch()});